Repository waycrate/swhkd, pull requests merged in 2022-02, with the labels that each got.

#23 Simpler IPC implementation using std::os::unix::net instead of using interprocess crate.
  Cargo.lock
  Cargo.toml
  Makefile
  src/daemon.rs
  src/server.rs
Labels: enhancement

#24 Config file handler by Angelo-F
  .github/workflows/ci.yml
  src/config.rs
  src/server.rs
Labels: enhancement

#33 Working keyevent handler
  README.md
  docs/INSTALL.md
  src/config.rs
  src/daemon.rs
Labels: bug, enhancement

#57 feat: add handling for comma maps inside braces
  docs/swhkdrc
  src/config.rs
  src/tests.rs
Labels: bug, enhancement

#55 Use evdev events instead of reading key state
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/daemon.rs
Labels: enhancement, help wanted
